site_name: Neutrino Group Documentation
theme:
  name: material
  palette:
    primary: dark-blue
    accent: light-blue
    scheme: light
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/neutrino-cern/neutrino-cern.github.io