site_name: Neutrino Group Documentation
theme:
  name: material
  palette:
    primary: dark-blue
    accent: light-blue
    scheme: light
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  


repo_url: https://github.com/neutrino-cern/neutrino-cern.github.io